# -*- coding: utf-8 -*-
"""AI Doucment Analyser & summariser

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k7yRRWDjzfVi4ogfkD4Q5WllaWtS3S0P
"""

!pip install -q groq pypdf python-docx langchain streamlit fastapi

import groq
print("Groq Installed Successfully")

from groq import Groq
import getpass

api_key = getpass.getpass("Enter your Groq API Key: ")

client = Groq(api_key=api_key)

print("✅ Groq Connected Successfully!")

from google.colab import files

uploaded = files.upload()

from pypdf import PdfReader
from docx import Document

filename = list(uploaded.keys())[0]

text = ""

if filename.endswith(".pdf"):
    reader = PdfReader(filename)
    for page in reader.pages:
        page_text = page.extract_text()
        if page_text:
            text += page_text + "\n"

elif filename.endswith(".docx"):
    doc = Document(filename)
    for para in doc.paragraphs:
        text += para.text + "\n"

print("✅ Document Loaded Successfully!")
print(text[:1000])   # First 1000 characters

response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {
            "role": "system",
            "content": "You are an AI Document Summarizer."
        },
        {
            "role": "user",
            "content": f"Summarize the following document:\n\n{text}"
        }
    ],
    temperature=0.3
)

summary = response.choices[0].message.content

print(summary)

response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {
            "role":"system",
            "content":"Extract the top 5 key insights from the document in bullet points."
        },
        {
            "role":"user",
            "content": text
        }
    ]
)

print(response.choices[0].message.content)

question = input("Ask a question about the document: ")

response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {
            "role":"system",
            "content":"Answer only from the uploaded document. If the answer is not in the document, say 'Not found in the document.'"
        },
        {
            "role":"user",
            "content": f"Document:\n{text}\n\nQuestion:\n{question}"
        }
    ]
)

print("\nAnswer:")
print(response.choices[0].message.content)

response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {
            "role": "system",
            "content": "Extract the important facts from the uploaded document in bullet points."
        },
        {
            "role": "user",
            "content": text
        }
    ]
)

key_facts = response.choices[0].message.content

print(" Key Facts:\n")
print(key_facts)

response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {
            "role": "system",
            "content": "Extract the 10 most important keywords from the document."
        },
        {
            "role": "user",
            "content": text
        }
    ]
)

keywords = response.choices[0].message.content

print(" Keywords:\n")
print(keywords)

response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {
            "role": "system",
            "content": "Generate a suitable title for this document."
        },
        {
            "role": "user",
            "content": text
        }
    ]
)

title = response.choices[0].message.content

print(" Suggested Title:")
print(title)

with open("AI_Report.txt", "w", encoding="utf-8") as f:
    f.write("===== DOCUMENT TITLE =====\n")
    f.write(title + "\n\n")

    f.write("===== SUMMARY =====\n")
    f.write(summary + "\n\n")

    f.write("===== KEY FACTS =====\n")
    f.write(key_facts + "\n\n")

    f.write("===== KEYWORDS =====\n")
    f.write(keywords)

print("✅ Report Saved Successfully")

from google.colab import files

files.download("AI_Report.txt")